name: Build and Deploy LaTeX CV

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up TeX Live
      run: source ./texlive_install.sh

    - name: Build LaTeX CV
      run: |
        mkdir _build
        pdflatex -output-directory _build ./curriculum-vitae.tex

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build
